### ISSUE TITLE
Aesthetic Programming

### ISSUE THREAD

**Issue by ivanreese** [ivanreese/visual-programming-codex#10]
This is a fantastic paper about the synthesis of artistic aesthetics, modelling, and systems: https://www.researchgate.net/publication/2517392

This *might* qualify as an example: http://psdoom.sourceforge.net/

**Comment by jackrusher** [comment]
Small world! I studied computer graphics with Fishwick in '89 or '90.

**Comment by ivanreese** [comment]
Small world indeed! I’m really excited to dig through Fishwick’s other papers, references, works that cite him, since this “let’s create explicit mappings between aesthetic attributes and modelled system attributes” idea is something that I’ve been really curious about. Any pointers to other works of his (or others) along these lines?

Thanks again for suggesting I start a repo for this stuff. It’s become a valuable aid in my research.

**Comment by jackrusher** [comment]
I can't, sadly. We studied out of the newly released second addition of [this book](https://en.wikipedia.org/wiki/Computer_Graphics:_Principles_and_Practice) and read a bunch of humanistic stuff, IIRC. It was almost 30 years ago, practically a different world!

Anyway, glad to see you keeping up with this. I've enjoyed eavesdropping on the repo. 😀
