### ISSUE TITLE
Dark Lang

### ISSUE THREAD

**Issue by nitincodery** [ivanreese/visual-programming-codex#116]
https://darklang.com/

**Comment by ivanreese** [comment]
Not sure how this counts as a visual language. Care to elaborate?

**Comment by nitincodery** [comment]
You're right it doesn't, I haven't used it in long time, and all I remembered about the darklang gui to make nodes of tasks graphically, I recently opened darklang and realized I'm wrong, it does not strictly qualify as a visual programming language due to its reliance on textual input rather than graphical representations.

**Comment by disconcision** [comment]
@nitincodery it used to have a more visual editor component (though mostly more structured editor style than VPL as-such); they've backed off on this aspect, similar to unison
