### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by jackrusher** [ivanreese/visual-programming-codex#2]
The current lists of projects are good, maybe add:

* [PAD3](https://www.youtube.com/watch?v=5JzaEUJ7IbE)

I would suggest the addition of a "notes" or some such more conceptual documentation category. To start, perhaps:

* [Deutsch Limit](https://en.wikipedia.org/wiki/Deutsch_limit)
* Stéphane Conversy's papers ([1](https://hal.inria.fr/hal-00737414),[2](https://dl.acm.org/citation.cfm?id=2661138))
* [The Cornell program synthesizer](https://dl.acm.org/citation.cfm?id=358755)

I'll dredge up more old stuff as time permits. :)

**Comment by ivanreese** [comment]
I've added those to the collection, and look forward to reviewing them over the coming months. Thank you!
